# 技术教程首页配置信息
# 下面内容中所有以 "#"" 开始的行都是注释行
# YAML 语法参考：http://yaml.org/spec/1.2/spec.html
---
# 导航栏配置
# 导航栏配置包含主题及主题下的所有标签
# 技术教程元信息中配置的标签都应是在导航栏配置中列出的标签
# 更新注释
nav:
  # 技术方向允许包含多个标签
  - topic: 后端开发
    tags:
      - name: Python
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Python.png
      - name: C++
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/C++.png
      - name: Java
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Java.png
      - name: C
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/C.png
      - name: Go
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Go.png
      - name: PHP
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/PHP.png
      - name: NodeJS
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/NodeJS.png
      - name: Ruby
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Ruby.png
      - name: 爬虫
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/WebCrawler.png
      - name: Django
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Django.png
      - name: Flask
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Flask.png
      - name: 机器学习
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Machine-Learnin.png
      - name: Git
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Git.png
      - name: Spring
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Spring.png
      - name: SSM
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/SSM.png
      - name: ThinkPHP
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/ThinkPHP.png
      - name: Laravel
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Laravel.png
      - name: R
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/R.png
      - name: Julia
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Default.png
      - name: OpenCV
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/OpenCV.png
  - topic: Web前端
    tags:
      - name: Web
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Web.png
      - name: Javascript
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/JavaScript.png
      - name: HTML
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/HTML.png
      - name: React
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/React.png
      - name: Vuejs
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Vuejs.png
      - name: CSS
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/CSS.png
      - name: Bootstrap
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Bootstrap.png
      - name: Electron
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Electron.png
      - name: Typescript
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Default.png
      - name: HTML5
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/HTML5.png
  - topic: Linux运维
    tags:
      - name: Linux
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Linux.png
      - name: 网络
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Network.png
      - name: Shell
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Shell.png
      - name: Ansible
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Ansible.png
      - name: Nginx
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Nginx.png
      - name: SDN
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/SDN.png
  - topic: 云计算与数据分析
    tags:
      - name: 机器学习
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Machine-Learnin.png
      - name: Docker
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Docker.png
      - name: Spark
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Spark.png
      - name: 云计算
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/CloudComputing.png
      - name: HBase
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/HBase.png
      - name: Hadoop
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Hadoop.png
      - name: Hive
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Hive.png
      - name: Kafka
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Kafka.png
      - name: Mahout
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Mahout.png
      - name: OpenStack
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/OpenStack.png
  - topic: 数据库
    tags:
      - name: SQL
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/SQL.png
      - name: MySQL
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/MySQL.png
      - name: NoSQL
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/NoSQL.png
      - name: MongoDB
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/MongoDB.png
      - name: Redis
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Redis.png
      - name: Influxdb
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Default.png
  - topic: 移动开发
    tags:
      - name: Android
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Android.png
      - name: iOS
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Default.png
      - name: Swift
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Swift.png
  - topic: 信息安全
    tags:
      - name: Kali
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Kali.png
      - name: Web安全
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Web-Security.png
      - name: 密码学
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/EncryptDecrypt.png
      - name: 信息隐藏
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/InformationHiding.png
      - name: 网络安全
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Network-Security.png
      - name: 安全开发
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Secure-Development.png
      - name: 渗透测试
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/PenetrationTest.png
      - name: 系统安全
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/System-Security.png
  - topic: 其他技术
    tags:
      - name: 算法
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Calculation.png
      - name: 区块链
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Blockchain.png
      - name: 编程基础
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Beginner.png
      - name: 职业生涯
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Default.png
      - name: 设计模式
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Design-Pattern.png
      - name: 机器人
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/ROS.png
      - name: Windows
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Windows.png
      - name: Git
        icon: https://dn-simplecloud.shiyanlou.com/tech-icon/Git.png

# 内容块配置
# 技术教程首页内容由若干个块组成，每一个块包含一个技术方向及其指定的教程
blocks:
  - topic: 后端开发
    books:
      - C++并发编程
      - JavaWeb入门开发教程
      - Gradle实战中文版
      - 新概念C语言
      - Go命令教程
      - php扩展开发及内核应用
      - php开发者实践
      - PHP进阶教程
      - Go入门指南
      - Node.js 教程
      - Sanic使用教程
      - twisted与异步编程入门
      - CGDB中文手册
      - Opencv中文文档(Python)
      - pyQT5教程
      - kotlin官方文档翻译
      - Julia中文文档
      - rails实践
      - Java并发知识点总结
      - Elasticsearch权威指南中文版
      - Java 学习+面试指南
      - Go语言高级编程
      - 关于Python的面试题
      - What the f**k Python
      - C语言编程透视
      - 互联网 Java 工程师进阶知识完全扫盲
      - Python 数据结构
  - topic: Web前端
    books:
      - CSS3教程
      - 前端开发者手册
      - javascript导学
      - 前端入门和进阶学习笔记
      - webpack中文指南
      - TypeScript使用手册
      - Gulp入门指南
      - ECMAScript 6入门
      - Redux简明教程
      - Redux中文文档
  - topic: Linux运维
    books:
      - 快乐的 Linux 命令行
      - Prometheus手册
      - 理解Linux进程
      - 像IDE一样实验Vim
      - Vim 实操教程
      - OpenResty最佳实践
      - Http API设计指南
      - Http接口设计指北
      - Shell 编程范例
      - Vim 从入门到精通
  - topic: 云计算与数据分析
    books:
      - 神经网络与深度学习
      - Keras中文文档
      - kubernetes中文指南
      - numpy用户指南
      - kubernetes完全教程
      - 算法/深度学习/NLP面试笔记
      - 机器学习基础
  - topic: 数据库
    books:
      - MongoDB小书
      - influxdb 简明教程
      - 使用Express+MongoDB搭建多人博客
  - topic: 其他技术
    books:
      - 实验楼使用指南
      - 如何做好一个程序员
      - 数据结构与算法/leetcode/lintcode题解
      - 程序员的自我修养
      - Go Ethereum
      - git菜单
      - gitlab-ci官方文档翻译
      - Git的奇技淫巧
      - 区块链教程
      - 十大经典排序算法
