# 1046102779/prometheus配置
---
# 技术教程名称应总是唯一的
name: Prometheus手册
# 技术教程 URL 链接定位字符串，通过 "-" 符号链接单词
slug: prometheus
topic: 云计算与数据分析
# 标签是一个有序列表，技术教程在页面显示时会使用第一个标签的 icon
tags:
  - Docker
# 技术教程所在的 git 仓库地址，仓库地址由 github 用户名和仓库名组成
repository: 1046102779/prometheus
# 技术教程所在的 git 仓库地址目录
# shiyanlou/library 下的技术教程需要指定教程章节内容所在的目录名称
# 而如果作者的技术教程拥有自己的仓库，则填写 "/" 即可
repository_dir: /
# 作者信息
# 如果同一作者拥有多个技术教程，所有教程的作者配置信息应一致
author:
  name: yellow chicks
  email: 
  # github 主页地址
  github: github.com/1046102779
  blog: github.com/1046102779
# 描述信息
description: |
  Prometheus官网的非官方中文手册，旨在为大家提供一个比较容易入手的文档。翻译得不好，请大家多多包涵，并帮忙修订校正 
# 配置教程是否该领域官方教程
official: false
# 教程版本号
version: 1.1
